name: Daily News Push
on:
  schedule:
    - cron: "10 23 * * *"  # 对应北京时间 7:10（UTC 时间 23:10）
  workflow_dispatch:  # 允许手动触发测试
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install requests
        run: pip install requests
      - name: Run news script
        run: python news.py
